name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: echo 'Hello, world!'
      - name: leadtime in seconds
        run: |
          ltag="$(git describe --abbrev=0)"
          echo "last tag: ${ltag}"
          echo "first commit since tag: $(git log --oneline ${ltag}..${GITHUB_REF} | awk '{print $1}' | tail -1)"
          t1="$(git log --oneline ${ltag}..${GITHUB_REF} | awk '{print $1}' | tail -1) xargs git show -s --format=%ci | tail)"
          echo "lead time in sec: $((date - ${t1}))"

