name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: echo 'Hello, world!'
      - name: show logs
        run: echo "$(git log --oneline | tail)"
      - name: leadtime in seconds
        run: |
          ltag="${git rev-parse --short $(git describe --abbrev=0))"
          echo "last tag: ${ltag}"
          lcommit="$(git rev-parse --short HEAD~1)"
          t1="$(git log --oneline ${ltag}..${lcommit} | awk '{print $1}' | tail -1) xargs git show -s --format=%ci | tail)"
          echo "lead time in sec: $((date - ${t1}))"

