name: "create a new release tag"
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: show PATH
        run: echo "{$PATH}"
      - name: install ghr
        run: |
          wget https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_linux_386.tar.gz -O - | tar xvz;
          sudo ln ghr_v0.13.0_linux_386/ghr /usr/local/bin
      - name: calcualte new release tag
        run: | 
          latestTag="$(git describe --tags --abbrev=0)"
          echo "::set-env name=newRelease::v$(( $(echo ${latestTag} | tr -dc 0-9) + 1 ))"
      - name: calculate leadtime
        run: bash .github/workflows/sample.sh ${newRelease}
      - name: run ghr
        run: ghr -t ${{ secrets.TOKEN }} ${newRelease}
      - uses: actions/upload-artifact@v1
        with:
          name: leadtime 
          path: output.txt

